### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by polichan** [JoeshuTT/version-polling#1]
```
export 'createVersionPolling' (imported as 'createVersionPolling') was not found in 'version-polling'
```

**Comment by wuzesen** [comment]
我也遇到了同样的问题

**Comment by JoeshuTT** [comment]
看下代码截图

**Comment by wuzesen** [comment]
1

**Comment by wuzesen** [comment]
import {createVersionPolling} from 'version-polling'


createVersionPolling({
  appETagKey: "__APP_ETAG__",
  pollingInterval: 5  * 1000, // 单位为毫秒-默认5分钟轮询一次
  silent: process.env.NODE_ENV === "abc", // 开发环境下不检测
  onUpdate: (self) => {
    // 当检测到有新版本时，执行的回调函数，可以在这里提示用户刷新页面
    const result = confirm("页面有更新，点击确定刷新页面！");
    if (result) {
      self.onRefresh();
    } else {
      self.onCancel();
    }
    // 强制更新可以用alert
    // alert('有新版本，请刷新页面');
  },
})

**Comment by wuzesen** [comment]
报错   warning  in ./src/main.js

export 'createVersionPolling' (imported as 'createVersionPolling') was not found in 'version-polling' (module has no exports)

**Comment by JoeshuTT** [comment]
我新开了一个空白vue项目，没有发现你这个错误
```
npm init vue
npm install
npm run dev
npm install version-polling
npm run build 
npm run preview
```
![image](https://github.com/JoeshuTT/version-polling/assets/22463804/61e9cf0f-6d2f-4403-b802-995d67dc57c8)

![image](https://github.com/JoeshuTT/version-polling/assets/22463804/921fa598-5b24-4386-ba27-b289f0389ff5)

**Comment by JoeshuTT** [comment]
或者你说下你下的 node环境， vue用的什么打包 viete 还是vuecli 等等

**Comment by JoeshuTT** [comment]
导入方式换下
 `import { createVersionPolling } from "version-polling/dist/version-polling.esm.js";`
