### ISSUE TITLE
关于onRefresh方法

### ISSUE THREAD

**Issue by daydayup001001** [JoeshuTT/version-polling#10]
查看源码如下：
onRefresh() {
      window.location.reload();
    }
 window.location.reload();方法相当于浏览器正常刷新，如果出现重新打包的情况，还是会使用原来的缓存文件。使用window.location.reload(true);会不会好点，相当于清空缓存的刷新

**Comment by JoeshuTT** [comment]
1. 打包文件有index.html js css，工程化项目 js都是hash处理过的。
刷新了html不就是用最新的html文件，script标签引入的文件也也是最新的，为啥会有存在你说的缓存文件
2. [forceGet](https://developer.mozilla.org/en-US/docs/Web/API/Location/reload#forceget) 这个属性浏览器支持度也有问题
![image](https://github.com/JoeshuTT/version-polling/assets/22463804/b20e2e74-37d2-4489-aaf2-754c09582722)
