### ISSUE TITLE
appETagKey字段

### ISSUE THREAD

**Issue by zhongyi07** [JoeshuTT/version-polling#11]
appETagKey字段唯一标识名啥意思

**Comment by JoeshuTT** [comment]
缓存标识。这个一般不用关心，localstorage里能看到。用来对比缓存 etag跟fetch html的etag，不一致就需要更新。

**Comment by zhongyi07** [comment]
那这个字段意思是自己随便定义一个是吧

**Comment by JoeshuTT** [comment]
都有默认值的，一般都不用关心的。

**Comment by zhongyi07** [comment]
ok，thx
