### ISSUE TITLE
 Error: [version-polling]: etag is null

### ISSUE THREAD

**Issue by shixiaoxianga** [JoeshuTT/version-polling#12]
代码如下
`
 createVersionPolling({
        appETagKey: "__DanDuoLA_APP__",
        pollingInterval: 3 * 1000,
        silent: !process.env.NODE_ENV === "development", // 开发环境下不检测
        onUpdate: (self) => {
          console.log('检测到新版本', self)
          this.newVersionDialog = { //确定对话框
            show: true,
            icon: "",
            msg: '发现了新版本！点击确认按钮刷新页面并更新',
            leftButton: "",
            rightButton: "确认",
            callback: (key) => {
              this.confirmDialog.show = false
              key === 'ok' ? self.onRefresh() : self.onCancel()
            },
            title: "提示",
            zIndex: 99999
          }
        },
      });

`
报错： Error: [version-polling]: etag is null
etag如何设置？

**Comment by JoeshuTT** [comment]
服务器需要配置协商缓存，就会有这个etagl，例如nginx自带。

**Comment by shixiaoxianga** [comment]
<img width="746" alt="image" src="https://github.com/user-attachments/assets/ccb16ba7-325d-4e52-b98f-59efc8105162">

<img width="607" alt="image" src="https://github.com/user-attachments/assets/65c082e4-6593-4fc9-b214-61d10d6bc75c">


<img width="783" alt="image" src="https://github.com/user-attachments/assets/85edd01e-613e-490f-8860-947986266eb5">


curl响应头有值，发送请求响应头就没有Etag，header是空对象，作者知道哪的问题吗，组件库是否可以支持自定义响应头例如X-Etag

**Comment by JoeshuTT** [comment]
1. 看不出来
2. 自定义响应头没有后端配合没有意义。
3. htmlFileUrl 就是index.html 的链接
4. 可以查查nginx 为什么请求响应头没有etag返回相关问题，是不是有什么其他配置项干扰。例如https://cloud.tencent.com/developer/ask/sof/116429084
