### ISSUE TITLE
fetch htmlFileUrl 状态码是404的时候，也会执行onUpdate回调

### ISSUE THREAD

**Issue by witcsmartian** [JoeshuTT/version-polling#3]
https://github.com/JoeshuTT/version-polling/blob/main/src/utils/index.ts#L40C33-L40C33

假定此时正在发版或者其它的操作，导致htmlFileUrl 不可访问，此时，从`   const etag = response.headers.get("etag");` 中得到etag 为 null，与lastEtag 不等，会触发onUpdate回调

**Comment by JoeshuTT** [comment]
好的，我抽时间改下。
建议发版时，应该先上传静态资源文件，最后在上传indehtml文件，这样可以保障发版前后，用户都可以正常使用。

**Comment by witcsmartian** [comment]
> 好的，我抽时间改下。 建议发版时，应该先上传静态资源文件，最后在上传indehtml文件，这样可以保障发版前后，用户都可以正常使用。

采用`nginx`静态部署的项目可能没问题，容器化部署的项目在`pod`重启的时候可能会502

**Comment by JoeshuTT** [comment]
v1.2.0已发布
- 修复fetch htmlFileUrl请求非200时不处理
- 新增属性配置silentPollingInterval
- 新增属性配置silentPageVisibility
- 新增属性配置forceUpdate
