### ISSUE TITLE
Vue项目使用有什么需要注意的吗？

### ISSUE THREAD

**Issue by yxplus1116** [JoeshuTT/version-polling#4]
现在遇到两个问题：
1.页面不可见后，任务停止，页面恢复后会立即只执行一次，但是不会实时去执行了。
 2.index.html 没有更新内容，但是等待 1 分钟左右，依然弹窗更新。
 对于 Vue 这种SPA 单页应用。htmlFileUrl: `${location.origin}`,是否是需要这样配置？

**Comment by JoeshuTT** [comment]
html 响应的header是否存在Etag字段
1. 你的配置参数是怎么样的，实时是看配置的几秒
2. 你的部署方式是怎么样的，HEAD请求的地址跟你实际部署的静态html地址是否一致？

**Comment by yxplus1116** [comment]
这是我的配置，确实页面只要由不可见回到可见状态，轮询就会失效，并且页面不可见一分钟后再回到页面，必现内容更新：<script src="https://unpkg.com/version-polling/dist/version-polling.min.js"></script>
  <script>
    const { createVersionPolling } = VersionPolling;
    createVersionPolling({
      appETagKey: "__APP_ETAG__",
      pollingInterval: 5 * 1000,
      htmlFileUrl: `${location.origin}`,
      onUpdate: (self) => {
        // 当检测到有新版本时，执行的回调函数，可以在这里提示用户刷新页面
        const result = confirm("页面有更新，点击确定刷新页面！");
        if (result) {
          self.onRefresh();
        } else {
          self.onCancel();
        }
      },
    });
  </script>

**Comment by JoeshuTT** [comment]
应该是你这个server microsoft-IIS设置了什么定时更新或者怎样，你资源内容没有变化，etag还会变。
插件是根据etag是否变化来检测更新的。
