### ISSUE TITLE
基于vue-cli项目，在入口文件引用以后报缺少loader的错误

### ISSUE THREAD

**Issue by young-3303** [JoeshuTT/version-polling#6]
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

**Comment by JoeshuTT** [comment]
给我看下你的package.json 文件

**Comment by young-3303** [comment]
> 载程序来处理此文件类

[package.json](https://github.com/JoeshuTT/version-polling/files/14326812/package.json)
请大佬看看

**Comment by JoeshuTT** [comment]
> Workaround:
> 
> ```js
> // vue.config.js
> module.exports = {
>   transpileDependencies: ['version-polling']
> }
> ```
参考[#6562 (comment)](https://github.com/vuejs/vue-cli/issues/6562#issuecomment-872784086)
我试过了打包ok，老项目更推荐script引入。

**Comment by young-3303** [comment]
> > Workaround:
> > ```js
> > // vue.config.js
> > module.exports = {
> >   transpileDependencies: ['version-polling']
> > }
> > ```
> 
> 参考[#6562 (comment)](https://github.com/vuejs/vue-cli/issues/6562#issuecomment-872784086) 我试过了打包ok，老项目更推荐script引入。

感谢大佬，这样确实可以了，只是还有点疑问transpileDependencies这个选项是用来转换ES6语法的，和loader有什么关系呢？我也看了源码，不存在缺少loader的情况，但是报错却是缺少loader
