### ISSUE TITLE
Content-Encoding导致ETag变化

### ISSUE THREAD

**Issue by d0apga** [JoeshuTT/version-polling#7]
线上部署好后，第一次请求：
![image](https://github.com/JoeshuTT/version-polling/assets/1168900/16df4205-1648-4878-9204-16911c200a44)
第二次请求：
![image](https://github.com/JoeshuTT/version-polling/assets/1168900/5ba4ea0d-c058-46a6-92c9-4d8c9dc09866)
由于Content-Encoding导致ETag变化，认为有更新，实际没有更新，这种情况如何避免？

**Comment by JoeshuTT** [comment]
又是这个Microsoft-IIS，之前还有人反馈，每过一分钟就会刷新etag，我不是很清楚这个server的更新机制。
前端换个库去解决或者后端server配缓存？

**Comment by d0apga** [comment]
目前把IIS的静态内容压缩功能关掉，使用UrlRewrite来输出gz文件就可以了
