### ISSUE TITLE
js文件加载不出来

### ISSUE THREAD

**Issue by HarveySupper** [JoeshuTT/version-polling#9]
![Snipaste_2024-04-12_11-30-25](https://github.com/JoeshuTT/version-polling/assets/133087169/c19609c4-08b1-4dac-98dd-8677326e24a2)
从昨天开始会频繁出现js文件加载不出来的问题，这个是因为什么额

**Comment by JoeshuTT** [comment]
是不是用的公共cdn地址，换成自己服务器的
